### ISSUE TITLE
Import/Export todos

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#1895]
With basically all of the old code ported to Rust, it's time to turn to new features and improvements. This issues is supposed to track such todos, which have previously been scattered across various PRs and issues.
Some discussion is on #1018 and this list will be updated according to the progression over there.

General
---

- [ ] Custom exporters/importers.

Apkg
---

- [x] Check invalid ids on import (ids 1000x too large).
- [ ] Notetype remapping on import.
- [ ] Private fields.
- [ ] Private tags.
- [x] Update with older mtime. (https://github.com/ankitects/anki/pull/2612)
- [ ] Generate cards on import (#1836).
- [x]  Populate media DB on import (#1831).
- [x] Export filtered decks (without conversion to regular ones). (https://github.com/ankitects/anki/pull/1743#discussion_r840255927)
- [ ] Warn about extraneous exported cards and decks due to scattered siblings.
- [x] Allow importing without scheduling, if file contains some. (https://github.com/ankitects/anki/pull/2612)

JSON
---

More notes on https://github.com/ankitects/anki/pull/1850#issuecomment-1122156181.
-   [ ] Validation checks.
-   [ ] Error handling. (More specific errors, don't abort if failure results from target collection state, ...)
-  [ ] Support importing new cards (https://github.com/ankitects/anki/pull/1850/files#r869037548.
-  [ ] Port SuperMemo and Pauker importers to JSON, or figure out if we can map the legacy NoteImporter code to JSON automatically (or semi-automatically)
- [ ] Extract Mnemosyne, SuperMemo and Pauker importers into separate add-ons

CSV
---

-  [x] Preview for first few records.
-  [x] Optionally export notetype and deck columns. (Let user decide if by name or id?)
-  [x] Handle failures in `GetCsvMetadata`.
-  [x] Support note id/guid column. (just guid)
-  [ ] Report unmapped columns.
-  [x] Maybe add tooltips to import options. (#2655)
-  [x] Restrict duplicate check to current deck (https://github.com/ankitects/anki/pull/2372)

From https://forums.ankiweb.net/t/import-problems-suggestions/5856. Might also apply to JSON.
- [ ] Batch importing.
- [ ] Import media files from same folder.
- [ ] Import notetypes.
- [x] Create decks on import.

**Comment by dae** [comment]
> Import deck options without scheduling information.

Not sure about this one. The styling/JS deck authors add to their shared decks are already a big source of issues, and allowing shared deck authors to push their option choices on users is likely to lead to confusion, and make support harder.

**Comment by dae** [comment]
>  Optionally export notetype and deck columns. (Let user decide if by name or id?)

Could we get away with just using a name?

**Comment by RumovZ** [comment]
> allowing shared deck authors to push their option choices on users is likely to lead to confusion, and make support harder.

That's from https://forums.ankiweb.net/t/stats-ruined-when-importing-decks-from-others/15901/3 which you've linked in #1018 (although I falsely wrote "import" instead of "export"). I don't mind scratching that.
But to pick up another thought from there: We could give users the option to _import_ without scheduling. This should be quite simple to implement.

> Could we get away with just using a name?

Probably a good compromise. Changing deck and notetype names should be rare enough to not cause too much inconvenience with exported CSVs.

**Comment by dae** [comment]
> We could give users the option to import without scheduling.

If we're presenting a dialog for other reasons as well, that's certainly a possibility. I suspect the fact that the new exporting code excludes scheduling by default will dramatically reduce the number of users accidentally importing scheduling in the future, but such an option could still potentially be useful for older exports.

**Comment by dae** [comment]
There's one for due numbers over a million, and a few caps applied in .sql files to ensure certain values fit in an i32 or u16. I'd also be wary about trying to automatically fix the problem due to the potential problems it could cause; I'd just been thinking we could detect such a case when importing, and present an error to the user like "This deck contains timestamps in the future. Please contact the deck author and ask them to fix the issue using the ... add-on."

cards/notes/revlog would be the big ones; we can always add others in the future if it still proves to be an issue

**Comment by njam** [comment]
Small note about the check making sure IDs are not in the future (added in https://github.com/ankitects/anki/pull/1928):
> This deck contains timestamps in the future. Please contact the deck author and ask them to fix the issue.

Some anki deck generator libraries are generating IDs based on the current timestamp, then adding one millisecond for each new ID (e.g. Rust [genanki-rs](https://github.com/yannickfunk/genanki-rs/blob/6ad21f7847012453567dacaa48b582d6f2c88506/src/package.rs#L137), Python [genanki](https://github.com/kerrickstaley/genanki/blob/0fa4f74f100c24738d3fbb542e3c81c07e5d6bf5/genanki/package.py#L39)). Obviously this will produce IDs in the future, and thus the import will fail, albeit not for too long.

I really don't know what is a good way to solve this, so I'm adding a comment here hoping somebody else knows more. I guess the root problem is that "id" must be a timestamp and must be unique, which is probably not easy to resolve :D

**Comment by RumovZ** [comment]
IIRC the main purpose was to reject microsecond timestamps, which caused issues when interpreted by Anki as ms timestamps. If it makes life easier for third-party libraries, there shouldn't be a problem with accepting timestamps from the near future (like 24h), or is there, @dae?

**Comment by dae** [comment]
Sounds reasonable, I'll push that through.

**Comment by RumovZ** [comment]
Optionally limiting the duplication check to the current deck is a common feature request. Should I add it to the list, @dae?

**Comment by dae** [comment]
If it can be done without a lot of code or a big slowdown, sounds good.

**Comment by youdontneedtoknow22** [comment]
This is probably off-topic and could be deleted, but I just wanted to get your attention on this bug (https://www.reddit.com/r/Anki/comments/zrlvwm/this_deck_contains_timestamps_in_the_future/) and the solution in the comments worked for me. I was exporting a really known Anki Deck in Germany for medical students (Zankiphil) using version 2.1.60

**Comment by dae** [comment]
This is covered on https://faqs.ankiweb.net/timestamps-in-the-future.html. Please use the forums if you have further questions.

**Comment by sdasda7777** [comment]
Hi, it appears that when you include a HTML file on a card (`<iframe src="file.html"></iframe>`) and export the card, the HTML file is not being exported and/or imported with no warnings whatsoever. Does that sound like an intentional decision or more of a bug?

**Comment by RumovZ** [comment]
@sdasda7777, see https://docs.ankiweb.net/media.html#checking-media. An underscore should also help with the export.
