### ISSUE TITLE
Migrate Test Suite from Jest to Deno

### ISSUE THREAD

**Issue by andrewpeters9** [ankitects/anki#2559]
* Serves as a non-committal preliminary move to Deno
* Can potentially lower complexity of tooling required for current Jest suite

**Tasks**

- [x] Explicify extension imports and exports (e.g. `./build` has to become `./build/index.ts` or `./build.ts`)
  - [x] Luckily there's a ESLint plugin for this
  - Deno requires it, and IMO it is probably a good thing in the long run
- [ ] Find a solution for DOM support within Deno, the below are the three potential libraries for DOM support
   - [ ] ❌ `JSDOM` - Deno previously supported it, but now no longer does. See here for an update on support https://github.com/denoland/deno/issues/18315
   - [ ] ❌ `deno-dom` - isn't as full-featured as JSDOM, would require changes to core files
   - [ ] ❌ `LinkeDom` - isn't as full-featured as JSDOM, would require changes to core files too
       - Example would be the use of `Range.startContainer` and `Range.startOffset` used in core files
       - These two methods aren't implemented in LinkeDom's Range: https://github.com/WebReflection/linkedom/blob/ec5ce8470c50fe2e9ea6e8b339e6ee4f23077c73/types/interface/range.d.ts
   - [ ]  🤔  Deno's [JSX](https://deno.land/manual@v1.36.1/advanced/jsx_dom/jsx) - yet to investigate, but I'm not too hopeful
- [x] Replace `jest` with the [bdd.ts](https://deno.land/manual@v1.36.1/basics/testing/behavior_driven_development) module
- [ ] Configure Rust build steps to include Deno testing etc.

**Overall Consensus:**
* Tests not involving JSDOM just work, but...
* (Pending investigation into Deno's JSX features) - I think `deno` generally isn't mature enough to migrate to right now.
* From what I can see right now, these would be the two solutions going forward, if you were still wanting to implement Deno:
  * Without changes to core files:
    * We would have to wait until Deno re-supports JSDOM
  * With changes to core files:
    * Either `deno-dom` or `LinkeDom` could be used, there would just have to be an assessment of how many core files would need to be changed

**Draft PR:**
If you were wanting to have a poke around at the changes yourself, you can have a look here, I've made a highlight in one of the tests that involve JSDOM to show you what kind of changes are necessary: https://github.com/andrewpeters9/anki/pull/2/files#diff-8fb68789875340806dc6afec3d580711479140115e0df0911455532663425ef8R1-R33

**Comment by andrewpeters9** [comment]
@dae Hey Damien, I've updated the above issue with my recent findings. It's looking like Deno may be a no-go, however, unfortunately.

**Comment by dae** [comment]
That's ok - 'not yet viable' was always a possibility, and Deno may still be a bit too new to justify spending an innovation token on. I still really appreciate you looking into it and posting your findings here.

I've recently been working with Sveltekit on the AnkiWeb end, which is based on Vite, and have found the HMR and separate dev/production bundling to be quite good, and it may be worth bringing this into Anki in the future as well. Currently our desktop is an MPA architecture, but in the long run I think we'll be better off with an SPA/router approach, so we don't incur the page load time each time the user navigates between pages.

Vite has its own alternative to Jest called Vitest that also might be worth exploring at some point, as it looks somewhat lighter-weight.

**Comment by andrewpeters9** [comment]
@dae 

> That's ok - 'not yet viable' was always a possibility, and Deno may still be a bit too new to justify spending an innovation token on. I still really appreciate you looking into it and posting your findings here.

I just reviewed my comments. I think I was maybe a bit too blunt with my words. Once `JSDOM` is supported in `deno` then I think it's likely a viable switch. It's just that that issue has been sitting dormant for one year now, so let's not hold out breath!

> I've recently been working with Sveltekit on the AnkiWeb end, which is based on Vite, and have found the HMR and separate dev/production bundling to be quite good, and it may be worth bringing this into Anki in the future as well. Currently our desktop is an MPA architecture, but in the long run I think we'll be better off with an SPA/router approach, so we don't incur the page load time each time the user navigates between pages.

Sounds like a task I'd be interested in helping out with. I can open up an issue for this the weekend after this one with potential steps on porting :)

**Comment by dae** [comment]
Hi Andrew,

To save you some time, some things I noticed while working on adding SvelteKit to AnkiWeb:

- Vite expects ESM inputs, so we need dependencies that support JS modules. IIRC, trying to import a JS dependency that is only in legacy UMD format will fail. There may be some of our existing dependencies where this applies.
- We'd need to update our package.json to include type: module
- We'd be moving from a single output .js/.css file to an unpredictable number of split files in a production build, so our build scripts would need to be updated to copy all files in that folder.
- Our frontend (and the mobile clients too, later), would need to change from loading eg. congrats.js to instead loading a URL like /congrats. Our backend (currently mediasrv.py) would need to serve the index.html file when that URL is requested, and it would need to match the routes defined in SvelteKit. 

Bringing it all together will be a decent amount of work. The first two points would be a good starter, as I presume we could do them while keeping our current architecture otherwise unchanged.

**Comment by dae** [comment]
After #3077, this no longer applies as we're using vitest now.
