### ISSUE TITLE
Post-Deno Conversion House-Keeping

### ISSUE THREAD

**Issue by andrewpeters9** [ankitects/anki#2560]
* Serves as a reminder for tasks that require attention following the (potential) removal of Node in favour of Deno

**Tasks:**

- [ ] Migrate `package.json` to `deno.json` once Deno is implemented, as [recommended here by the Deno core team](https://deno.com/manual@v1.34.3/node/package_json#packagejson-compatibility)
  - [ ] First, ascertain importance of the core team's recommendations, and evaluate whether Anki should stick to a `package.json` file
- [ ] Replace `npm:` prefixed packages with their respective Deno packages
- [ ] Replace `node:` prefixed packages with their respective Deno packages
- [ ] ❌ Migrate linting suite to `deno lint`
  - [ ] Ascertain pros/cons first
- [ ] TO BE ADDED TO OVER TIME

**Comment by dae** [comment]
Not sure if switching to deno lint is practical at the moment - we use an eslint plugin so that our svelte files are also checked, and another eslint plugin to check if the APIs we're using are valid for our browser targets.

**Comment by andrewpeters9** [comment]
> 

Good point. Removed it from the list.

**Comment by dae** [comment]
Closing this, as the deno migration stalled. Thank you for the work you put into it, in any case!
